# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF#refs/heads/}
  build:
    uses: FcoJunior/actions/.github/workflows/build.yml@main
  test:
    uses: FcoJunior/actions/.github/workflows/test.yml@main
    needs: build
  deploy:
    uses: FcoJunior/actions/.github/workflows/deploy.yml@main
    needs: [build, test]
